model:
  type: diffusion
  network: gadiff
  hidden_dim: 128
  num_convs: 4
  cutoff: 10.0
  mlp_act: relu
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  num_diffusion_timesteps: 5000
  edge_order: 3
  edge_encoder: mlp
  smooth_conv: true

  edge_type_func:                 # node attention
    input_dim: 4
    output_dim: 4
    hidden_dim: 128
    layer_num: 3
    head_num: 16
    drop_rate: 0.001

  weight_func:                    # noise attention
    input_dim: 4
    output_dim: 4
    hidden_dim: 384
    layer_num: 3
    head_num: 8
    drop_rate: 0.001

train:
  seed: 2023
  batch_size: 100
  batch_num: 2000
  val_freq: 1
  max_iters: 500
  model_max_grad_norm: 30000.0
  modelw_max_grad_norm: 30000.0
  anneal_power: 2.0
  accum_iter: 1

  model_para:
    optimizer:
      type: adam
      lr: 5.e-4
      weight_decay: 0.
      beta1: 0.95
      beta2: 0.999
    # scheduler:
    #   type: plateau
    #   factor: 0.6
    #   patience: 10
    scheduler:
      type: defined
      init_lr: 5.e-4
      max_iters: 1000000
      min_lr: 0.
      warmups: 60000

dataset:
  train: /home/a45/wangdh/code/data/Drugs/train_data_40k.pt
  val: /home/a45/wangdh/code/data/Drugs/val_data_5k.pt
  test: /home/a45/wangdh/code/data/Drugs/ConfGF_Test/test_data_200.pt
